# Generated by Django 5.2.1 on 2025-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_staff_student_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
    ]
