# Generated by Django 5.2.1 on 2025-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_staff_student_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardianEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
